# Generated by Django 6.0.3 on 2026-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=150, verbose_name='Scientific name')),
                ('common_name', models.CharField(max_length=250, verbose_name='Common name')),
                ('group', models.CharField(max_length=100, verbose_name='Spicies group')),
                ('conservation_status', models.CharField(max_length=10, verbose_name='Conservation')),
                ('image', models.URLField(verbose_name='image URL')),
            ],
        ),
    ]
